name: bomp
channels:
  - plotly
  - conda-forge
  - defaults
dependencies:
  - spyder
  - ipywidgets=7.5
  - jupyterlab
  - pandas
  - pyarrow
  - plotly
  - python-kaleido
  - nodejs
  - seaborn
  - aiohttp
  - aiodns
  - cchardet
  - pytest
  - pytest-cov
