name: bomp
channels:
  - plotly
  - conda-forge
  - defaults
dependencies:
  - aiodns=2.0.0
  - aiohttp=3.6.2
  - async-timeout=3.0.1
  - attrs=19.3.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - brotlipy=0.7.0
  - ca-certificates=2020.6.20
  - certifi=2020.6.20
  - cffi=1.14.1
  - chardet=3.0.4
  - cloudpickle=1.5.0
  - colorama=0.4.3
  - decorator=4.4.2
  - idna=2.10
  - ipykernel=5.3.4
  - ipython=7.17.0
  - ipython_genutils=0.2.0
  - jedi=0.15.2
  - jupyter_client=6.1.6
  - jupyter_core=4.6.3
  - libsodium=1.0.17
  - multidict=4.7.5
  - openssl=1.1.1g
  - parso=0.8.0
  - pickleshare=0.7.5
  - pip=20.2.2
  - plotly=4.9.0
  - prompt-toolkit=3.0.6
  - pycares=3.1.1
  - pycparser=2.20
  - pygments=2.6.1
  - python=3.8.5
  - python-dateutil=2.8.1
  - python-kaleido=0.0.3
  - python_abi=3.8
  - pywin32=227
  - pyzmq=19.0.2
  - retrying=1.3.3
  - setuptools=49.6.0
  - six=1.15.0
  - spyder-kernels=1.9.3
  - sqlite=3.32.3
  - tornado=6.0.4
  - traitlets=4.3.3
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - wcwidth=0.2.5
  - wheel=0.35.1
  - wincertstore=0.2
  - yarl=1.3.0
  - zeromq=4.3.2
