name: bomp
channels:
  - plotly
  - conda-forge
  - defaults
dependencies:
  - nest-asyncio
  - pyarrow = 1.0.1
  - cchardet
  - aiodns
  - aiohttp
  - pytest-cov
  - python-kaleido
  - pandas
  - plotly
  - pytest
  - requests
  - spyder-kernels
  - python
  - jupyterlab
  - ipywidgets
  - matplotlib
  - seaborn
  - nodejs
