name: bomp
channels:
  - plotly
  - conda-forge
  - defaults
dependencies:
  - nest-asyncio
  - pyarrow
  - cchardet
  - aiodns
  - aiohttp
  - pytest-cov
  - python-kaleido
  - pandas
  - plotly
  - pytest
  - requests
  - spyder-kernels
  - python
  - jupyterlab
  - ipywidgets
  - bs4
  - black
  - line_profiler
  - scikit-learn
  - matplotlib
  - seaborn
