name: Build
# This workflow is triggered on pushes to the repository.
on: 
  push:
    paths:
    - 'src/**.py'
    - 'tests/**.py'
    - '.github/workflows/build-test.yml'
  workflow_dispatch:


jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Load conda package cache
        uses: actions/cache@v2
        env:
          # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yml') }}-

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.0.1
        with:
          channels: plotly,conda-forge,defaults
          auto-activate-base: false
          environment-file: environment.yml
          activate-environment: bomp
          use-only-tar-bz2: true
          auto-update-conda: true
          
      - name: Display conda env
        shell: bash -l {0}
        run: |
          pwd
          conda info
          conda list

      - name: Run tests and coverage
        shell: bash -l {0}
        run: |
          pwd
          ls
          pytest test_environment.py --cov=src --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          files: ./coverage1.xml,./coverage2.xml
          env_vars: OS,PYTHON
          fail_ci_if_error: false
