name: Test Code
# This workflow is triggered on pushes to the repository.
on: [push]


jobs:
  example-3:
    name: Ex3 Linux
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
          mamba-version: "*"
          activate-environment: bomp
          environment-file: environment.yml
          use-only-tar-bz2: true
          auto-activate-base: false
      - shell: bash -l {0}
        run: |
          conda info
          conda list